default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: jaime_johnson_development

test:
  <<: *default
  database: jaime_johnson_test

staging:
  <<: *default
  database: jaime_johnson_staging

production:
  <<: *default
  database: jaime_johnson_production
